image: volodyalarin/tp_cpp_course_env:ubuntu

variables:
  COVER_LOG: cover.log
  PROG: voyager
  UNIT: gtest
  LINTER: linter.sh
  VALGRIND_LOG: valgrind.log
  NO_LOST_PATTERN: "All heap blocks were freed -- no leaks are possible"
  NO_ERROR_PATTERN: "ERROR SUMMARY: 0 errors"


stages:
  - test_style
  - build
  - test

test_style:
  stage: test_style
  script:
    - sh ./${LINTER}
  needs: [ ]

build:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - cmake -B ./build
    - make -C ./build
  needs: [ ]
  artifacts:
    paths:
      - ./build
      - ./cmake-modules
    expire_in: 15 minutes


unit_tests:
  stage: test
  script:
    - cd build && ./${UNIT}
  needs: [ "build" ]

coverage:
  stage: test
  script:
    - cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make coverage > ${COVER_LOG}
    - cat ${COVER_LOG}
  artifacts:
    paths:
      - ./build/${COVER_LOG}
  needs: [ "build" ]

memory:
  stage: test
  script:
    - valgrind --tool=memcheck --leak-check=summary --log-file=${VALGRIND_LOG} ./build/${UNIT}
    - export NO_LOST=$(grep "${NO_LOST_PATTERN}" ${VALGRIND_LOG})
    - export NO_ERROR=$(grep "${NO_ERROR_PATTERN}" ${VALGRIND_LOG_DATA})
    - if [ -z "${NO_LOST}" ] || [ -z "${NO_ERROR}" ]; then cat ${VALGRIND_LOG}; exit 1; fi
  artifacts:
    paths:
      - ./${VALGRIND_LOG}
  needs: [ "build" ]
